site_name: Architecture & AI Wiki
theme:
  name: material
  custom_dir: docs/stylesheets
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Software Architecture:
      - Architerual Views: software-architecture/architectural-views.md
      - Design Principles: software-architecture/design-principles.md
      - Patterns:
          - Microservices: software-architecture/patterns/microservices.md
          - Layered: software-architecture/patterns/layered.md
  - AI:
      - Prompt Engineering: ai/prompt-engineering.md
  - Blog:
      - 2025-06-01: blog/2025-06-01-why-event-driven-architecture-scales.md
